---
- name: main / (Debian) Install and Update apt packages.
  apt:
    name: "{{ item }}"
    state: present
    update_cache: yes
  loop:
    - "apache2"
    - "apache2-utils"
    - "git"
    - "wget"
    - "tar"
    - "python3"
    - "python3-pip"
    - "bash-completion"
    - "chrony"
    - "tree"
  when: "ansible_os_family == 'Debian'"
