---
# tasks file for ./roles/packages
- name: main / Add the OS specific variables
  include_vars: "{{ ansible_os_family }}.yml"

- include_tasks: apt_update.yml
  when: ansible_os_family == 'Debian'

- include_tasks: dnf_update.yml
  when: ansible_os_family == 'RedHat'

- name: main / Install the required packages
  package:
    name: "{{ required_packages }}"
    state: present

- name: main / nodes rebooting...
  reboot:
    reboot_timeout: 300
  changed_when: False
