---
- name: main / (RedHat) Deploy /etc/chrony.conf
  copy:
    src: redhat.conf
    dest: /etc/chrony.conf
    owner: root
    group: root
    mode: 0644
  when: ansible_os_family == 'RedHat'

- name: main / (Debian) Deploy /etc/chrony/chrony.conf
  copy:
    src: debian.conf
    dest: /etc/chrony/chrony.conf
    owner: root
    group: root
    mode: 0644
  when: ansible_os_family == 'Debian'

- name: main / Restart chronyd Service
  systemd:
    name: chronyd
    state: restarted
    enabled: yes
  changed_when: False
