---
- name: Initialize OS setting for Linux Servers
  hosts: node
  become: true

  roles:
    - name: common/firewall
      tags: "firewall"
    - name: common/selinux
      tags: "selinux"
      when: ansible_os_family == 'RedHat'
    - name: common/packages
      tags: "packages"
    - name: common/locale
      tags: "locale"
    - role: common/users
      tags: "users"
    - name: common/resolver
      tags: "resolver"
    - name: common/chronyd
      tags: "chronyd"
    - name: common/apache
      tags: "apache"

  post_tasks:
    - name: initalized. nodes rebooting...
      reboot:
      changed_when: False

    - name: Waiting connection
      wait_for_connection:
        delay: 5
        timeout: 60
